[package]
name = "elliptic-sys"
version = "0.1.0"
authors = ["Jihyeok Seo <limeburst@member.fsf.org>"]
license = "GPL-3.0"
build = "build.rs"

[build-dependencies]
gcc = "0.3.17"

[dependencies]
libc = "0.1.10"
